### ISSUE TITLE
无法使用 $\hbar$ 输入普朗克常数。

### ISSUE THREAD

**Issue by Sollovin** [Lianghao93/HUST-PhD-Thesis-Latex-v3.1#2]
报错信息如下：
```
ERROR: Undefined control sequence.

--- TeX said ---
\hbar ->\protect \hbar  
                        
l.33 $ \hbar
             = 1 $
```

**Comment by Lianghao93** [comment]
试一下$\hslash$
以及推荐加一下我们的QQ群782574845，群里回复会更及时，我现在毕业了GitHub这边维护很少
![1708EAE5537BECEA700F421A18F54BEE](https://github.com/Lianghao93/HUST-PhD-Thesis-Latex-v3.1/assets/32161863/a71a38d1-10db-41aa-96d8-819530efbfc7)

**Comment by Sollovin** [comment]
好的，已加群。我暂时用 hslash 替代。
但这个问题好修复吗？

**Comment by Lianghao93** [comment]
https://www.zhihu.com/question/374252861
可能是字体包冲突导致的，你可以参考一下这里的方法在HUSTtils.sty添加一个宏包：
\usepackage{mathpazo}

**Comment by Sollovin** [comment]
查到了，`HUSTthesis.cls` 文件里 153 行配置的 `mathptmx` 包会导致这个问题。

**Comment by Sollovin** [comment]
因为学校要求英文必须用 `times`， 一种更合适的解决方案也许是替换 `HUSTthesis.cls` 里 153 行配置的 `mathptmx` 包为 `newtxmath` 。
